
```{r}
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(knitr)
questions <- read_csv('questions.csv')
answers <- read_csv('answers.csv')
tags <- read_csv('tags.csv')
question_tags <- read_csv('question_tags.csv')
questions
answers
tags
question_tags
```
1. Left-joining questions and tags

```{r}
questions_with_tags <- questions %>% 
  left_join(question_tags, by=c("id" = "question_id")) %>% 
  left_join(tags, by = "id") %>% 
  replace_na((list(tag_name = "only-r")))
questions_with_tags
```
2.Comparing scores across tags

```{r}
mean_score <- questions_with_tags %>% 
  group_by(tag_name) %>% 
  summarise(avg=mean(score))
  arrange(mean_score, desc(avg))
```
3. Finding gaps between questions and answers

```{r}
answers
questions %>% 
  inner_join(answers, by=c("id" = "question_id"), suffix=c("_question", "_answer")) %>% 
  mutate(gap = creation_date_question - creation_date_answer)
```
4. Joining question and answer counts

```{r}
answer_counts <- answers %>% 
  arrange(desc(question_id)) %>% 
  count(question_id, sort = T) 
question_answer_counts <- questions %>% 
  left_join(answer_counts, by=c("id" = "question_id")) %>% 
  replace_na((list(n = 0)))
question_answer_counts
```
5. Joining questions, answers, and tags

```{r}
question_tags %>% 
  inner_join(question_answer_counts, by=c("question_id" = "id")) %>% 
  inner_join(tags, by=c("question_id" = "id"))
```
