
Construyendo la variable diamonds y validando estrucutra con la funcion str
```{r}
diamonds <- read_csv('diamonds.csv')
show_col_types = FALSE

str(diamonds)

```
1. Grafico de Dispersion

```{r}
library(ggplot2)

ggplot(diamonds, aes(x=carat, y = price)) +
geom_point()

```
1.2, 1.3. Mapeando el color con la variable clarity 

```{r}
ggplot(diamonds, aes(x=carat, y = price, color=clarity)) +
geom_point()
```
2. Histograma

2.1. Geometria Histograma

```{r}
ggplot(diamonds, aes(x=price)) + 
  geom_histogram(bins = 40)

```
2.2. Agregando logartmica de base 10.

```{r}
ggplot(diamonds, aes(x=price)) + 
  geom_histogram(bins = 40)+
  scale_x_log10()
```
3. BoxPlots

3.1. Grafico BoxPlots

```{r}

ggplot(diamonds, aes(x=cut, y=price)) +
  geom_boxplot() + 
  scale_y_log10()
```
3.2. Editando color de cada caja parametro fill

```{r}
ggplot(diamonds, aes(x=cut, y=price, fill = cut)) +
  geom_boxplot() + 
  scale_y_log10()
```
4. Faceting

4.1
```{r}
Filtered_price1 <-  filter(diamonds, price > 1000, cut %in% c("Good", "Ideal", "Premium"))
Filtered_price1
```
4.2.

```{r}
ggplot(Filtered_price1, aes(x=cut,y=depth))+
  geom_bar(stat="identity")


```
4.3.
```{r}
ggplot(Filtered_price1, aes(x=cut,y=depth))+
  geom_bar(stat="identity")+
  facet_wrap(~clarity)
```
4.4.

```{r}
ggplot(Filtered_price1, aes(x=cut,y=depth, fill = clarity))+
  geom_bar(stat="identity")+
  facet_wrap(~clarity)
```
Grouping And Summarizing 
1.
```{r}
median_dimension_diamond <- diamonds %>%
group_by(cut) %>%
  summarize(Mediax = median(x), Mediay = median(y), Mediaz = median(z))

median_dimension_diamond
```
2. 
```{r}
cut_premium <- diamonds %>%
  filter(cut == "Premium") %>%
  group_by(clarity) %>%
  summarize(MinPrice = min(price), MaxPrice = max(price))

cut_premium
   
```

3.

```{r}

ggplot(cut_premium, aes(x=clarity,y=MaxPrice, fill = clarity))+
  geom_bar(stat="identity")

```

